spring:
  application:
    name: user-service
  profiles:
    active: '@env@'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sleuth:
    sampler:
      percentage: 1
nacos:
  config:
    server-addr: '@config.address@'
    namespace: '@namespace@'
logging:
  level:
    root: 'debug'
  file:
    path: ''
